name: Build

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload coverage to Teamscale
      if: always() && github.event_name == 'push'
      run: |
        curl -L -o teamscale-upload.zip https://github.com/cqse/teamscale-upload/releases/download/v1.0.0/teamscale-upload-linux.zip
        unzip teamscale-upload.zip
        ./teamscale-upload \
          -s https://demo.teamscale.com/ \
          -p teamscale-jacoco-agent \
          -u build \
          -a $ACCESS_KEY \
          -t Coverage \
          -f JACOCO \
          --message Coverage \
          --detect-commit \
          **/jacocoTestReport.xml
    - name: Publish to Maven Central
      run: |
        ./gradlew publishMavenPublicationToMavenRepository \
          -Psigning.secretKeyRingFile=$TRAVIS_BUILD_DIR/.gnupg/secring.gpg \
          -Psigning.password=$MAVEN_CENTRAL_GPG \
          -Psigning.keyId=4FB80B8E \
          -PsonatypeUsername=cqse-build-guild \
          -PsonatypePassword=$SONATYPE_PW \
          -Porg.gradle.internal.http.connectionTimeout=500000 \
          -Porg.gradle.internal.http.socketTimeout=500000
    - name: Upload Release Assets
      if: startsWith(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: '{agent/build/distributions/teamscale-jacoco-agent.zip,javaws-wrapper/build/distributions/javaws.zip}'
        file_glob: true
        overwrite: true
